addons:
  apt:
    packages:
      - docker-ce

sudo: required

services:
  - docker

before_script:
  - docker build -t runner .

script:
  - docker run --rm runner 2>&1 | grep -q "Building Runner Failed"