language: node_js
node_js:
    - node

before_script:
    - npm install
script:
    - npm test

before_deploy:
    - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GH_TOKEN
  on:
    branch: master